#!/usr/bin/env python3
"""Deterministic CHANGELOG.md, regenerated whole from git.

The commit convention (`type(scope): subject`, subject-only) is
the input format, so the changelog is pure derivation: the same
tags and commits always render the same file, newest release
first, commits grouped by type in a fixed order. There is no
hand-maintained state to drift; "updating" the changelog means
regenerating it, the same stance the minutes renderer takes.

Usage:
  scripts/changelog.py            regenerate CHANGELOG.md
  scripts/changelog.py --check    exit 1 if CHANGELOG.md is stale
  scripts/changelog.py --notes vX.Y.Z
                                  print one release's section body
                                  (for the release notes)
  scripts/changelog.py --release vX.Y.Z
                                  regenerate WITH a pending
                                  section for the tag about to be
                                  cut (last tag..HEAD, dated
                                  today)

The release commit itself (`chore(release): ...`) is skipped,
so the file generated BEFORE that commit exists is byte-equal
to a regeneration after the tag lands on it; `--check` stays
green across the boundary.

Exit 0 on success (and on a clean --check), 1 on a stale check
or unknown tag, 2 on a usage error.
"""

import re
import subprocess
import sys

OUT = "CHANGELOG.md"
MARKER = "<!-- @generated by scripts/changelog.py -->"
TYPE_ORDER = ["feat", "fix", "perf", "refactor", "docs", "test", "chore"]
TYPE_TITLES = {
  "feat": "Features",
  "fix": "Fixes",
  "perf": "Performance",
  "refactor": "Refactoring",
  "docs": "Documentation",
  "test": "Tests",
  "chore": "Chores",
  "other": "Other",
}
SUBJECT = re.compile(r"^(\w+)(?:\(([^)]*)\))?: (.+)$")
RELEASE_COMMIT = re.compile(r"^chore\(release\)")


def git(*args):
  return subprocess.run(
    ["git", *args], capture_output=True, text=True, check=True
  ).stdout


def version_key(tag):
  return [int(p) for p in tag.lstrip("v").split(".")]


def tags():
  raw = git("tag", "--list", "v*").split()
  return sorted(raw, key=version_key)


def tag_date(tag):
  return git(
    "log", "-1", "--format=%cs", f"{tag}^{{commit}}"
  ).strip()


def commits(rev_range):
  out = git(
    "log", "--no-merges", "--reverse", "--format=%h%x00%s", rev_range
  )
  rows = []
  for line in out.splitlines():
    if "\x00" not in line:
      continue
    short, subject = line.split("\x00", 1)
    if RELEASE_COMMIT.match(subject):
      continue
    rows.append((short, subject))
  return rows


def render_section(tag, prev, rev_tip=None):
  tip = rev_tip or tag
  rev = f"{prev}..{tip}" if prev else tip
  grouped = {}
  for short, subject in commits(rev):
    m = SUBJECT.match(subject)
    kind = m.group(1) if m and m.group(1) in TYPE_ORDER else "other"
    grouped.setdefault(kind, []).append((short, subject))
  date = (
    __import__("datetime").date.today().isoformat()
    if rev_tip
    else tag_date(tag)
  )
  lines = [f"## {tag} ({date})", ""]
  for kind in TYPE_ORDER + ["other"]:
    if kind not in grouped:
      continue
    lines.append(f"### {TYPE_TITLES[kind]}")
    lines.append("")
    for short, subject in grouped[kind]:
      m = SUBJECT.match(subject)
      body = m.group(3) if m and m.group(1) in TYPE_ORDER else subject
      scope = m.group(2) if m else None
      prefix = f"**{scope}**: " if scope else ""
      lines.append(f"- {prefix}{body} ({short})")
    lines.append("")
  return "\n".join(lines).rstrip() + "\n"


def render(pending=None):
  all_tags = tags()
  parts = [MARKER, "# Changelog", ""]
  if pending and pending not in all_tags:
    prev = all_tags[-1] if all_tags else None
    parts.append(render_section(pending, prev, rev_tip="HEAD"))
  for i, tag in enumerate(reversed(all_tags)):
    idx = len(all_tags) - 1 - i
    prev = all_tags[idx - 1] if idx > 0 else None
    parts.append(render_section(tag, prev))
  return "\n".join(parts).rstrip() + "\n"


def main():
  args = sys.argv[1:]
  if args and args[0] == "--notes":
    if len(args) != 2:
      print("usage: changelog.py --notes vX.Y.Z", file=sys.stderr)
      return 2
    tag = args[1]
    all_tags = tags()
    if tag not in all_tags:
      print(f"unknown tag {tag}", file=sys.stderr)
      return 1
    idx = all_tags.index(tag)
    prev = all_tags[idx - 1] if idx > 0 else None
    section = render_section(tag, prev)
    # Body only: drop the "## vX (date)" heading line.
    print("\n".join(section.splitlines()[2:]))
    return 0
  if args and args[0] == "--release":
    if len(args) != 2:
      print("usage: changelog.py --release vX.Y.Z", file=sys.stderr)
      return 2
    open(OUT, "w").write(render(pending=args[1]))
    print(f"wrote {OUT} (pending {args[1]})")
    return 0
  fresh = render()
  if args and args[0] == "--check":
    try:
      current = open(OUT).read()
    except FileNotFoundError:
      current = ""
    if current != fresh:
      print(f"{OUT} is stale; run scripts/changelog.py", file=sys.stderr)
      return 1
    print(f"{OUT} is current")
    return 0
  if args:
    print(__doc__, file=sys.stderr)
    return 2
  open(OUT, "w").write(fresh)
  print(f"wrote {OUT}")
  return 0


if __name__ == "__main__":
  sys.exit(main())
